apiVersion: v1
kind: ReplicationController
metadata:
  name: mylogin-rc
spec:
  replicas: 2
  selector:
    app: mylogin
    version: 1.1.1
  template:
    metadata:
      labels:
        app: mylogin
        version: 1.1.1
    spec:
      containers:
        - name: mylogin-container
          image: maha4iac/myonlinebooking:1
          ports:
            - containerPort: 8080
