apiVersion: v1
kind: Service
metadata:
  name: myloginapp-SVC
  labels:
    app: mylogin
    version: 1.1.1
spec:
  type: NodePort
  ports:
  - port: 8080
    nodePort: 30001
    protocol: TCP
  selector:
    app: mylogin
    version: 1.1.1